### ISSUE TITLE
Page for tweet list

### ISSUE THREAD

**Issue by mdrouhard** [hds-lab/coding-ml#68]
1.  Each list item includes tweet text, time of tweet, time last updated by coders
2. List of tweets may be ordered by: random, tweet time, "ambiguity"/disagreement prediction
3. Sublime-like list location overview visualization (consistent between coding interface & tweet list) - points in list visualization are "highlighted" for current view in list page - coding page visualization will only show current tweet as "highlighted"
4. Navigation: Clicking on tweet takes user to coding interface for selected tweet.  After submitting codes, tweets will be ordered according to order selected in list view
5. Navigation: Page tabs allow user to navigate back to coding interface or review interface

**Comment by jinasuh** [comment]
We changed the design
